# Generated by Django 4.2.5 on 2023-10-22 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name_plural': '3.Course'},
        ),
        migrations.AlterModelOptions(
            name='coursecategory',
            options={'verbose_name_plural': '2.Course Categories'},
        ),
        migrations.AlterModelOptions(
            name='students',
            options={'verbose_name_plural': '4.Students'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name_plural': '1.Teachers'},
        ),
    ]
